export const TEMPLATES = [
  {
    id: "classic",
    name: "Classic Single-Column",
    badge: "Max ATS B&W",
    desc: "100% monochrome, high parsing rate, single-column layout for automated ATS scanners.",
    defaultAccent: "#111111",
    supportsPhoto: false,
  },
  {
    id: "modern",
    name: "Modern Split Two-Column",
    badge: "Most Popular",
    desc: "Dedicated sidebar for contact, skills, and education; spacious main area for experience and projects.",
    defaultAccent: "#1e3a5f",
    supportsPhoto: true,
  },
  {
    id: "tech",
    name: "Minimalist Tech",
    badge: "Engineers",
    desc: "Monospace accents, inline tech stack badges, terminal-inspired styling for developers.",
    defaultAccent: "#0f766e",
    supportsPhoto: false,
  },
  {
    id: "executive",
    name: "Executive Header",
    badge: "Leadership",
    desc: "Full-width colored header band with contact, distinguished typography, and formal dividers.",
    defaultAccent: "#1e293b",
    supportsPhoto: true,
  },
  {
    id: "compact",
    name: "Compact High-Density",
    badge: "High-Density",
    desc: "Tight line-height, optimized padding, and compact section headers to fit extensive careers cleanly.",
    defaultAccent: "#2563eb",
    supportsPhoto: false,
  },
  {
    id: "slate",
    name: "Corporate Slate",
    badge: "Refined Serif",
    desc: "Slate-blue borders, refined serif typography, and formal executive structure.",
    defaultAccent: "#334155",
    supportsPhoto: false,
  },
  {
    id: "creative",
    name: "Creative Sidebar",
    badge: "Orange Gradient",
    desc: "Vibrant orange gradient sidebar with circular photo and modern icon contact list.",
    defaultAccent: "#ea580c",
    supportsPhoto: true,
  },
  {
    id: "academic",
    name: "Academic / CV",
    badge: "Scholarly",
    desc: "Scholarly layout prioritizing Education, Publications, Research, and Teaching credentials.",
    defaultAccent: "#831843",
    supportsPhoto: false,
  },
  {
    id: "timeline",
    name: "Timeline",
    badge: "Visual Rail",
    desc: "Subtle vertical rail with milestone dots tracking your professional career trajectory.",
    defaultAccent: "#0284c7",
    supportsPhoto: false,
  },
  {
    id: "modular",
    name: "Modular Card Grid",
    badge: "Modern Grid",
    desc: "Bordered cards with subtle shadows organizing your experience, projects, and skills into clean panels.",
    defaultAccent: "#4f46e5",
    supportsPhoto: true,
  },
];
